export const indexableGuideSlugs = [
  "how-to-get-your-bond-back-nsw",
  "how-to-get-your-bond-back-vic",
  "how-to-get-your-bond-back-qld",
  "how-long-does-bond-refund-take",
  "fair-wear-and-tear-australia",
  "can-landlord-charge-for-painting",
  "can-landlord-charge-for-carpet-cleaning",
  "end-of-lease-cleaning-checklist",
  "rental-bond-dispute-guide",
  "break-lease-costs-australia",
  "rent-increase-rules-australia",
  "moving-house-checklist",
  "rental-inspection-checklist",
  "how-to-dispute-bond-deductions",
  "bond-cleaning-cost-guide",
  "end-of-lease-cleaning-cost",
  "tenant-rights-bond-refund",
  "normal-wear-and-tear-examples",
  "landlord-deduction-examples",
  "rental-bond-refund-letter-template",
  "end-of-lease-photo-checklist",
  "how-to-prepare-for-final-inspection",
  "bond-refund-mistakes-to-avoid",
  "bond-refund-for-sharehouses",
  "breaking-lease-without-penalty",
  "rent-affordability-guide",
  "how-much-rent-can-i-afford-australia",
  "rent-to-income-ratio-calculator-australia",
  "30-percent-rent-rule-australia",
  "moving-costs-australia",
  "bond-loans-explained",
  "rental-application-costs",
  "first-time-renter-guide",
  "state-by-state-bond-guide",
  "sydney-bond-refund-guide",
  "melbourne-bond-refund-guide",
  "brisbane-bond-refund-guide",
  "perth-bond-refund-guide",
  "adelaide-bond-refund-guide",
  "canberra-bond-refund-guide",
  "sydney-end-of-lease-cleaning-costs",
  "melbourne-end-of-lease-cleaning-costs",
  "brisbane-end-of-lease-cleaning-costs",
  "sydney-moving-costs",
  "melbourne-moving-costs",
  "brisbane-moving-costs",
  "sydney-rent-increase-guide",
  "melbourne-rent-increase-guide",
  "brisbane-rent-increase-guide",
  "sydney-break-lease-costs",
  "melbourne-break-lease-costs",
  "brisbane-break-lease-costs",
  "carpet-cleaning-bond-deduction",
  "oven-cleaning-bond-deduction",
  "wall-marks-bond-deduction",
  "unpaid-rent-bond-deduction",
  "sharehouse-bond-split",
  "bond-refund-without-condition-report",
  "agent-claiming-more-than-bond"
] as const;

const indexableGuideSlugSet = new Set<string>(indexableGuideSlugs);

export function isIndexableGuide(slug: string) {
  return indexableGuideSlugSet.has(slug);
}
